Upgrade cryptography and pyopenssl
Upgrade the `cryptography` and `pyopenssl` packages to their latest
versions by running:

    make requirements --always-make args='--upgrade-package cryptography --upgrade-package pyopenssl'

When trying to run Via HTML on a Mac with Apple Silicon it's crashing
when trying to compile the ancient version of `cryptography` that Via
HTML depends on:

    fatal error: 'openssl/opensslv.h' file not found

I think `cryptography` publish pre-compiled binary wheels for Apple
Silicon so `pip` shouldn't need to compile it. I suspect that the old
version of `cryptography` has no Apple Silicon pre-compiled binary so
that's why it's trying to compile it.

Fix this by upgrading `cryptography` to the latest version.

Also upgrade `pyopenssl` at the same time, otherwise the tests fail
because the old version of `pyopenssl` doesn't work with the latest
`cryptography`:

    viahtml/app.py:10: in <module>
        from pywb.apps.frontendapp import FrontEndApp
    .tox/tests/lib/python3.8/site-packages/pywb/apps/frontendapp.py:9: in <module>
        from wsgiprox.wsgiprox import WSGIProxMiddleware
    .tox/tests/lib/python3.8/site-packages/wsgiprox/wsgiprox.py:15: in <module>
        from certauth.certauth import CertificateAuthority
    .tox/tests/lib/python3.8/site-packages/certauth/certauth.py:6: in <module>
        from OpenSSL import crypto
    .tox/tests/lib/python3.8/site-packages/OpenSSL/__init__.py:8: in <module>
        from OpenSSL import crypto, SSL
    .tox/tests/lib/python3.8/site-packages/OpenSSL/crypto.py:1517: in <module>
        class X509StoreFlags(object):
    .tox/tests/lib/python3.8/site-packages/OpenSSL/crypto.py:1537: in X509StoreFlags
        CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
    E   AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

Slack threads:

* https://hypothes-is.slack.com/archives/C1MA4E9B9/p1664885019098739
* https://hypothes-is.slack.com/archives/C4K6M7P5E/p1664808083310179